on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: requirements.*.txt
      - run: pip install sdist
      - run: pip install -e '.[dev]'
      - run: pylint text_analyzer -j 4 --reports=y --disable=missing-docstring

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: requirements.*.txt
        env:
          ANALYZER_API_KEY: ziax
      - run: pip install -U pip
      - run: pip install -Ue '.[dev]'
      - run: pytest tests --cov=text_analyzer --cov-report=term-missing --cov-fail-under 85

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: make docker

      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          repository: alksglk/text_analyzer
          target: api
          tags: 0.0.1, latest
